// category = ['meat-and-poultry', 'canned-goods', 'pasta-and-rice', 'baking-items', 'snacks', 'breakfast-foods', 'nuts-and-seeds', 'mixes', 'vinegars-and-cooking-wines', 'oils', 'sauces', 'condiments', 'sweets-and-candy', 'pickled-items', 'cereals', 'spices', 'beverages', 'root-vegetables', 'breads', 'soups', 'fruits-and-vegetables', 'pet-food', 'beans-and-legumes', 'jellies-and-spreads', 'canned-meats', 'miscellaneous' ]

export const categoryArr = [
	'All',
	'meat-and-poultry',
	'fruit-and-vegetables',
	'dairy',
	'canned-goods',
	'pasta-rice-bread',
	'baking-items',
];

export const pantryArr = [
	{
		id: 1,
		category: 'meat-and-poultry',
		name: 'whole-chicken',
		createdAt: '01-02-2021',
		expiry: '2021-03-21',
		weight: 8,
		unit: 'grams',
		quantity: 2,
		imageSrc: 'https://res.cloudinary.com/dt69gb9me/image/upload/v1622329152/whole-chicken_bv5yuu.png',
		notes: 'Don’t forget to pluck the feathers.',
	},
	{
		id: 2,
		category: 'meat-and-poultry',
		name: 'Beef-Tenderloin',
		createdAt: '01-04-2021',
		expiry: '2021-05-21',
		weight: 3,
		unit: 'grams',
		quantity: 3,
		imageSrc: 'https://res.cloudinary.com/dt69gb9me/image/upload/v1622329487/beef-tenderloin_ualddp.png',
		notes: 'Cut against the grain.',
	},
	{
		id: 3,
		category: 'meat-and-poultry',
		name: 'lamb-chops',
		createdAt: '01-03-2021',
		expiry: '2021-05-29',
		weight: 10,
		unit: 'grams',
		quantity: 1,
		imageSrc: 'https://res.cloudinary.com/dt69gb9me/image/upload/v1622329679/lamb-chops_jyjxco.png',
		notes: 'Remove the thick exterior fat layer and any silverskin underneath.',
	},
	{
		id: 4,
		category: 'meat-and-poultry',
		name: 'turkey-legs',
		createdAt: '01-03-2021',
		expiry: '2021-06-25',
		weight: 5,
		unit: 'grams',
		quantity: 6,
		imageSrc: 'https://res.cloudinary.com/dt69gb9me/image/upload/v1622329783/turkey-leg_aeuq2x.png',
		notes: 'It might be too salty for you so make sure it’s the main ingredient.',
	},
	{
		id: 5,
		category: 'meat-and-poultry',
		name: 'pork-chops',
		createdAt: '01-03-2021',
		expiry: '2021-05-23',
		weight: 6,
		unit: 'grams',
		quantity: 1,
		imageSrc: 'https://res.cloudinary.com/dt69gb9me/image/upload/v1622329951/pork-chops_p2puog.png',
		notes: 'Brine for more tender and flavourful pork chops.',
	},
	{
		id: 6,
		category: 'baking-items',
		name: 'sugar',
		createdAt: '01-03-2021',
		expiry: '2021-05-26',
		weight: 2,
		unit: 'grams',
		quantity: 5,
		imageSrc: 'https://res.cloudinary.com/dt69gb9me/image/upload/v1622330056/sugar_yvb7pd.png',
		notes: 'Naturally occurring sugar - like sugar in fruit and milk.',
	},

	{
		id: 7,
		category: 'fruit-and-vegetables',
		name: 'apple',
		createdAt: '01-03-2021',
		expiry: '2021-05-30',
		weight: 2,
		unit: 'grams',
		quantity: 5,
		imageSrc: 'https://res.cloudinary.com/dt69gb9me/image/upload/v1622330301/apple_nfpcdc.png',
		notes: 'Apples are fat free, saturated fat free, sodium free, cholesterol free and an excellent source of fiber',
	},
	{
		id: 8,
		category: 'canned-goods',
		name: 'baked-beans',
		createdAt: '01-03-2021',
		expiry: '2021-04-27',
		unit: 'grams',
		weight: 2,
		quantity: 5,
		notes: 'Contains parboiled beans.',
		imageSrc: 'https://res.cloudinary.com/dt69gb9me/image/upload/v1622330440/baked-beans_omywgt.png',
	},
	{
		id: 9,
		category: 'dairy',
		name: 'cheese',
		createdAt: '01-03-2021',
		expiry: '2021-04-15',
		weight: 2,
		unit: 'grams',

		quantity: 4,
		imageSrc: 'https://res.cloudinary.com/dt69gb9me/image/upload/v1622330543/cheese_edmgbq.png',
		notes: 'C',
	},
	{
		id: 10,
		category: 'pasta-rice-bread',
		name: 'bread',
		createdAt: '01-03-2021',
		expiry: '2021-06-11',
		weight: 2,
		unit: 'grams',
		quantity: 5,
		imageSrc: 'https://res.cloudinary.com/dt69gb9me/image/upload/v1622330677/bread_ketvok.png',
		notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit Iaculis enim, velit turpis eget. Fames erat mollis et, aliquam, pulvinar',
	},
];

