const pantryTypes = {
	CREATE_PANTRY_ITEM: 'CREATE_PANTRY_ITEM',
	REMOVE_PANTRY_ITEM: 'REMOVE_PANTRY_ITEM',
	EDIT_PANTRY_ITEM: 'EDIT_PANTRY_ITEM',
	SET_QUERY: 'SET_QUERY',
	SET_RECIPE
	SET_ITEM_NAME: 'SET_ITEM_NAME',
	FILTER_PANTRY_CHIP: 'FILTER_PANTRY_CHIP',
	GET_PANTRY_DETAIL: 'GET_PANTRY_DETAIL',
	GET_RECIPE_DETAIL: 'GET_RECIPE_DETAIL',
	FETCH_RECIPES_PENDING: 'FETCH_RECIPES_PENDING',
	FETCH_ALL_RECIPES_SUCCESS: 'FETCH_ALL_RECIPES_SUCCESS',
	FETCH_MED_RECIPES_SUCCESS: 'FETCH_MED_RECIPES_SUCCESS',
	FETCH_ASIAN_RECIPES_SUCCESS: 'FETCH_ASIAN_RECIPES_SUCCESS',
	FETCH_RECIPES_ERROR: 'FETCH_RECIPES_ERROR',
	SHOW_FETCH_RECIPE_BTN: 'SHOW_FETCH_RECIPE_BTN'
};

export default pantryTypes;