const pantryTypes = {
	CREATE_PANTRY_ITEM: 'CREATE_PANTRY_ITEM',
	REMOVE_PANTRY_ITEM: 'REMOVE_PANTRY_ITEM',
	EDIT_PANTRY_ITEM: 'EDIT_PANTRY_ITEM',
	SET_QUERY: 'SET_QUERY',
	SET_ITEM_NAME: 'SET_ITEM_NAME',
	FILTER_PANTRY_CHIP: 'FILTER_PANTRY_CHIP',
	GET_PANTRY_DETAIL: 'GET_PANTRY_DETAIL',
	FETCH_RECIPES_PENDING: 'FETCH_RECIPES_PENDING',
	FETCH_RECIPES_SUCCESS: 'FETCH_RECIPES_SUCCESS',
	FETCH_RECIPES_ERROR: ''
};

export default pantryTypes